const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.wrap,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Plugins.Keyboard,
		C3.Behaviors.Follow,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Button,
		C3.Plugins.Audio,
		C3.Plugins.TiledBg,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Follow.Acts.FollowObject,
		C3.Behaviors.Follow.Acts.StopFollowing,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayoutByName
	];
};
self.C3_JsPropNameTable = [
	{Wrap: 0},
	{Background: 0},
	{Solid: 0},
	{Platforms: 0},
	{Platform2: 0},
	{Platform3: 0},
	{ScrollTo: 0},
	{Platform: 0},
	{Zero: 0},
	{Keyboard: 0},
	{Building: 0},
	{Pillar: 0},
	{Platform1: 0},
	{FlyingPlatform2: 0},
	{Building1: 0},
	{censor: 0},
	{Follow: 0},
	{Guard: 0},
	{Building2: 0},
	{GuardStop: 0},
	{Sprite: 0},
	{Touch: 0},
	{Retry: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{HELP: 0},
	{Sprite4: 0},
	{PERSON: 0},
	{Text: 0},
	{Mouse: 0},
	{HELPUS: 0},
	{oui: 0},
	{transfer: 0},
	{Sprite5: 0},
	{chair: 0},
	{Ripperhouse: 0},
	{guide: 0},
	{Audio: 0},
	{TiledBackground: 0},
	{Sprite6: 0},
	{BlackBox: 0},
	{Credits: 0}
];

self.InstanceType = {
	Background: class extends self.ISpriteInstance {},
	Platforms: class extends self.ISpriteInstance {},
	Platform2: class extends self.ISpriteInstance {},
	Platform3: class extends self.ISpriteInstance {},
	Zero: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Building: class extends self.ISpriteInstance {},
	Pillar: class extends self.ISpriteInstance {},
	Platform1: class extends self.ISpriteInstance {},
	FlyingPlatform2: class extends self.ISpriteInstance {},
	Building1: class extends self.ISpriteInstance {},
	censor: class extends self.ISpriteInstance {},
	Guard: class extends self.ISpriteInstance {},
	Building2: class extends self.ISpriteInstance {},
	GuardStop: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Retry: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	HELP: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	PERSON: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	HELPUS: class extends self.IButtonInstance {},
	oui: class extends self.ITextInstance {},
	transfer: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	chair: class extends self.ISpriteInstance {},
	Ripperhouse: class extends self.ISpriteInstance {},
	guide: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	BlackBox: class extends self.ISpriteInstance {},
	Credits: class extends self.ISpriteInstance {}
}